version: "3.8"

services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: capstone13_admin
      POSTGRES_PASSWORD: capstone13_passwd
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ~/capstone/capstone_map:/capstone_map

volumes:
  postgis_data:
