version: "3.8"

services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./data:/capstone_map

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dzx@dzx.com
      PGADMIN_DEFAULT_PASSWORD: dzx123123
    ports:
      - "8080:80"
    depends_on:
      - postgis
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgis_data:
  pgadmin_data:
