import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


class Config:
    """Base configuration class"""

    # Get SECRET_KEY, use default value if not found in .env
    SECRET_KEY = (
        os.environ.get("SECRET_KEY") or "a-very-secret-key-that-should-be-changed"
    )

    # Database configuration
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_DATABASE_URI = os.environ.get("POSTGRES_DSN")


class DevelopmentConfig(Config):
    """Development environment configuration"""

    DEBUG = True
    SQLALCHEMY_ECHO = True  # Print SQL statements generated by ORM


# Map configuration classes to configuration names
config = {
    "development": DevelopmentConfig,
    "default": DevelopmentConfig,
}
